spring.application.name=auth-service
server.port=8091

# Database - Docker konteyner nomi (auth-db) ishlatiladi
spring.datasource.url=jdbc:postgresql://${DB_HOST:auth-db}:5432/${DB_NAME:auth_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Deploy uchun 'update' yaxshiroq, har safar DBni o'chirib yubormaydi
spring.jpa.hibernate.ddl-auto=update

# Java 21 Virtual Threads
spring.threads.virtual.enabled=true

# EMAIL SOZLAMALARI
spring.mail.host=mail.artstation.uz
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:it@artstation.uz}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false

# Dinamik IP (Email link uchun)
app.server.ip=${SERVER_PUBLIC_IP:170.168.6.99}
app.gateway.port=${GATEWAY_PORT:8090}