spring.application.name=auth-service

# Server port
server.port=8081
#
# Database (har bir service uchun alohida DB)
spring.datasource.url=jdbc:postgresql://auth-db:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

# Virtual threads (Java 21)
spring.threads.virtual.enabled=true

# EMAIL SOZLAMALARI (artstation.uz uchun)
spring.mail.host=mail.artstation.uz
spring.mail.port=465
spring.mail.username=it@artstation.uz
spring.mail.password=]V_yq{1DgUcMq&o[
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false