services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: ${DB_NAME:-auth_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8091:8091"
    environment:
      # Ma'lumotlar bazasi ulanishi
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/${DB_NAME:-auth_db}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-1234}

      # Email va Linklar uchun .env dan olinadigan ma'lumotlar
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SERVER_PUBLIC_IP: ${SERVER_PUBLIC_IP}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - app-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "${GATEWAY_PORT:-8090}:8090"
    depends_on:
      - auth-service
    networks:
      - app-network

  ui-service:
    build:
      context: ./lock-info-ui
    container_name: ui-service
    ports:
      - "5173:80"
    depends_on:
      - gateway-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge