spring.application.name=gateway-service
server.port=8090

# Spring Cloud Gateway konfiguratsiyasi
spring.cloud.gateway.routes[0].id=auth-service

# Docker ichida servislar bir-birini nomi bilan taniydi
spring.cloud.gateway.routes[0].uri=http://auth-service:8091
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

logging.level.org.springframework.cloud.gateway=DEBUG
spring.main.web-application-type=reactive

# Keraksiz avtokonfiguratsiyalarni cheklash
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration, org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration