spring.application.name=gateway-service

# Gateway port
server.port=8080

# Spring Cloud Gateway konfiguratsiyasi
spring.cloud.gateway.routes[0].id=auth-service
#spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
logging.level.org.springframework.cloud.gateway=DEBUG

spring.main.web-application-type=reactive
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration, org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration